USE [master]
GO

/****** Object:  Database [BlessTrading]    Script Date: 1/24/2022 2:07:08 AM ******/
CREATE DATABASE [BlessTrading]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlessTrading_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MARS\MSSQL\DATA\BlessTrading_Data.mdf' , SIZE = 16512KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'BlessTrading_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MARS\MSSQL\DATA\BlessTrading_Log.ldf' , SIZE = 5120KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
GO

ALTER DATABASE [BlessTrading] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlessTrading].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BlessTrading] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BlessTrading] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BlessTrading] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BlessTrading] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BlessTrading] SET ARITHABORT OFF 
GO

ALTER DATABASE [BlessTrading] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BlessTrading] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BlessTrading] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BlessTrading] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BlessTrading] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BlessTrading] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BlessTrading] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BlessTrading] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BlessTrading] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BlessTrading] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BlessTrading] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BlessTrading] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BlessTrading] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BlessTrading] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BlessTrading] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BlessTrading] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BlessTrading] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BlessTrading] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BlessTrading] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BlessTrading] SET  MULTI_USER 
GO

ALTER DATABASE [BlessTrading] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BlessTrading] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BlessTrading] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BlessTrading] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BlessTrading] SET  READ_WRITE 
GO

